### ISSUE TITLE
Slimraw compressed DNG files do not open

### ISSUE THREAD

**Issue by larssteenhoff** [octopuscinema/raw-player#11]
I have here two .DNG files created by Sigma FP and then converted to lossless compressed with Slimraw 
( https://www.slimraw.com )

https://www.dropbox.com/s/exehkhx884anv4u/A001_005_20220409_000001.DNG?dl=0

One is compressed with premiere cc compatible on and the other without.

https://www.dropbox.com/s/mtx0q9nhxglizns/B001_005_20220409_000001.DNG?dl=0

Both have an error when opening in RawPlayer

![Screenshot 2022-12-17 at 10 59 47](https://user-images.githubusercontent.com/9589240/208236471-fe9ee368-8e6b-49f1-a914-9490e7e0208d.png)

**Comment by octopus-russell** [comment]
This is something we are aware of, unfortunately it requires some re-writing of the lossless jpeg decoder - not a quick fix :( . It is in the road map for the first quarter of 2023.

**Comment by octopus-russell** [comment]
We have completed a rewrite of the lossless decompression code which now supports SlimRAW. This will be released as part of the next major revision at the end of the month

**Comment by larssteenhoff** [comment]
> We have completed a rewrite of the lossless decompression code which now supports SlimRAW. This will be released as part of the next major revision at the end of the month

Great to hear that!
