### ISSUE TITLE
Yellow cast on all CDNG clips

### ISSUE THREAD

**Issue by mbrendano** [octopuscinema/raw-player#12]
Hi there :)

My BMCC 2.5k CDNG clips are showing in your player with the same yellow cast that the finder previews them with -- I know that this is not how the clip really looks because when I open it in DaVinci its color balance looks fine. Can I fix this on my end, or are you working on a fix? 

Thanks!
Brendan

**Comment by octopus-russell** [comment]
Closing due to lack of acitivity
