### ISSUE TITLE
Does not play 8-bit Sigma fp content

### ISSUE THREAD

**Issue by gulliverity** [octopuscinema/raw-player#2]
It does not matter if I drop the first frame file or the whole folder of a sigma fp CDNG RAW movie onto the viewer window. Playback is an all-black movie.

**Comment by octopus-russell** [comment]
Hi gulliverity,

Thanks for being our first reported issue!

Would you be able to share two .dng frames and a screenshot of the clip metadata panel for the clip assuming the metadata is loading. (Clip metadata can be found under the 'Clip' -> 'Metadata...' menu)

If possible, could you also share the application log file. (located under the 'Help' -> 'Troubleshooting' -> 'View Log' menu)
Just a quick heads up - the 10-bit code path for CinemaDNG is not fully implemented yet - 12-bit and 8-bit are.

Thanks
Russell

**Comment by gulliverity** [comment]
Hi, Russell.
 
Much appreciation for the rapid response. Due to that, I just tried accessing another clip, this time confirmed as 12bit. Success!
 
The earlier attempts were with 8bit, though, and should be working per your response. Attached is the log file, two frames and the screenshot of the playback & metadata windows.
 
Request: could you look at the future release having the application’s icon being drag ‘n’ drop aware, please. Because the application auto-quits as soon as the sole playback window is closed, it’s a painful extra step to have to keep opening the application, seeing a playback window generated, then drop a folder onto it. Alternately, why not add a Command-N function for New Window. Am guessing that this being the first release, it can only handle one video stream at a time?
 
Thanks!
 
David
<img width="803" alt="Screenshot 2022-10-31 at 15 33 05" src="https://user-images.githubusercontent.com/117116595/199123804-5ea04478-8bbc-46f9-b439-6b417bdb97a0.png">
[OCTOPUS RAW Player.log](https://github.com/octopuscinema/raw-player/files/9905475/OCTOPUS.RAW.Player.log)
[Archive.zip](https://github.com/octopuscinema/raw-player/files/9905478/Archive.zip)

**Comment by octopus-russell** [comment]
Thanks David for sharing those items. That's great to see it works with 12-bit files! As you say there appears to be an issue with the app handling 8-bit sigma fp DNGs. I think we should have a fix for this pretty quick - into the next patch release which will be in a couple of days.

That is interesting regarding the drag 'n' drop - we have drag 'n' drop for the application window but it looks like dropping onto the dock icon requires a separate code implementation. We'll have a look at the complexity but I would imagine its fairly low hanging fruit - would probably go into the next minor release.

Currently the MacOS version supports one open clip with one open instance of the application - multiple windows/tabs is something we're thinking about but it would probably be much further into the future.

**Comment by gulliverity** [comment]
I noted in my comment on Newsshooter.com that you ultimately should be charging $10-$20 for this product. There's nothing else like it out there for those of us who need it.

As for the multiple windows topic, you might consider a half measure in the short term. Closing the open window does not quit the application. Then a NEW window player can be opened. Or even if closing the player window auto-generates a new player window instead of quitting. Just a thought...

**Comment by octopus-russell** [comment]
Thanks for the support, we do actually have a donations ko-fi page ;) we are giving it away as free open-source as we want to encourage open-source workflows.
The 8-bit DNG bug is now fixed in v1.0.2. Also in 1.0.2 there is now drag 'n drop and 'open with' file association support for macOS and Windows
1.0.2 will be available to download on the RAW Player home page in ~48 hours.
