### ISSUE TITLE
10bit CDNG sigma FP - Error:NotImplmeneted

### ISSUE THREAD

**Issue by Deef78** [octopuscinema/raw-player#21]
Hello, 
I wanted to try Octopus Raw Player with CDNG videos captured with a Sigma FP (25fps 10bits 9/16). 
None of the videos open, and an error message appears: "Failed to Open '....' Error: NotImplemented." 

I contacted your Instagram page, which redirected me here, explaining that 10bits is not yet implemented and requesting examples of videos to help resolve the issue. 

Here are two 10bits videos (in a 9/16 ratio):    https://www.swisstransfer.com/d/30fe9f18-f23e-4596-82a0-07b91cbd354e    (3,4Go) 

Error screen:
![2024-02-08 14 20 02](https://github.com/octopuscinema/raw-player/assets/142586639/a2a9fee9-349b-49ef-8713-dffb0024e521)

**Comment by octopus-russell** [comment]
Hi, thanks for sharing the sample, I can confirm 10-bit support wasn't yet implemented. It will make it into the next release which should be around the end of the month.

**Comment by octopus-russell** [comment]
10-bit support now released in v1.1.1

**Comment by Deef78** [comment]
hello, I tried it, thank you it works now! 

I just have a cache problem (I guess) because the video has to be played 2-3 times before it is perfectly smooth. Before that I have time jumps.  As I make short videos so it's not very a problem but for long videos it could be annoying.
