### ISSUE TITLE
reveal current frame in finder

### ISSUE THREAD

**Issue by larssteenhoff** [octopuscinema/raw-player#6]
When scrubbing trough a clip it wold be nice to have an option reveal the current time frame DNG in the finder
This would allow me the locate the frame I found and send it so someone for example, or open it in photoshop.

Additionally it would be nice if the player had an option to show the current playtime full .dng file name.

**Comment by octopus-russell** [comment]
This is now implemented in v1.0.3

**Comment by larssteenhoff** [comment]
> This is now implemented in v1.0.3

Thanks, this works really well!
