### ISSUE TITLE
Playback of cdng coming from MLV files

### ISSUE THREAD

**Issue by dannephoto** [octopuscinema/raw-player#7]
Tested on Mac OS Monterey 12.2.1
Files seems to play in correct order and in realtime. However preview is completely green.
Since we are at it. Eos m and other digic V canon cameras can manipulate pixels to achieve a better output. For instance 1x3 pixel modification which creates a very anamorphic output needs to be corrected. This could be done by addressing the default scale tag in cdng metadata. Only program I know atm using this tag is adobe camera raw.
Anyway. Not sure how deep you are willing to go around these files but a good looking preview would be nice to have to start with. I´ll provide a few sequences here.
[M10-0942_1_2022-11-10_0001_C0000.zip](https://github.com/octopuscinema/raw-player/files/9978281/M10-0942_1_2022-11-10_0001_C0000.zip)
[M10-0941_1_2022-11-10_0001_C0000.zip](https://github.com/octopuscinema/raw-player/files/9978282/M10-0941_1_2022-11-10_0001_C0000.zip)
[M10-0938_1_2022-11-10_0001_C0000.zip](https://github.com/octopuscinema/raw-player/files/9978283/M10-0938_1_2022-11-10_0001_C0000.zip)

**Comment by octopus-russell** [comment]
Thanks for sharing those. We've fixed the green issue - a colour maths bug with DNGs with forward matrices. It should make it into the next minor release which will be next week.
Implementing the scale tag looks like not a massive task - we'll try to schedule it in.

**Comment by dannephoto** [comment]
Nice one 👌

**Comment by octopus-russell** [comment]
Green MLV fixed and default scale tag implemented for 1.0.3 release

**Comment by dannephoto** [comment]
Sounds good. I´ll await the release.
